global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'linux_metrics'
    static_configs:
      - targets: ['EXPORTER_ADDRESS:9100']
